# Generated by Django 2.2.3 on 2019-08-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_use_ExternalUser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(blank=True, choices=[('1', 'critical'), ('2', 'major'), ('3', 'minor'), ('4', 'internal')], max_length=10, null=True),
        ),
    ]
